### ISSUE TITLE
Hello，编译 pbrt-v3 的时候出现了一点问题，想请教

### ISSUE THREAD

**Issue by OscarShen** [zq317157782/raiden#1]
我刚入手 pbrt 第三版，可是与 pbrt-v2 不同，我研究了两天无法编译成功，想要请教一下：
我使用 CMAKE 编译以后，ALL_BUILD，生成失败，试图只生成 libpbrt 也失败。主要有3个问题：
1、INT_MIX ... 等 宏重定义
2、glog.lib 缺失
3、libpbrt.lib 缺失
请问一下正确的编译顺序是什么？我应该下载哪些工具呢？
最后，我使用的是VS2015，WIN10。
如果你能指导我一下，我真的非常感谢。

**Comment by zq317157782** [comment]
不好意思，爱莫能助，PBRT_v3我没有编译过，我直接是重写PBRT_v3的
